default:
  image: ubuntu:20.04
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.8 python3-pip
    - apt -y upgrade
    - pip3 install -r requirements.txt


migrations:
  stage: build
  script:
    - python3 manage.py makemigrations
    - python3 manage.py makemigrations $CI_PROJECT_NAME
    - python3 manage.py migrate
    - python3 manage.py migrate $CI_PROJECT_NAME
    - python3 manage.py check


django-tests:
  stage: test
  script:
    - python3 manage.py test
