name: mule composite
on:
  push:
    branches:
      # - master/*
      - main
jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - name: checkout local repo
        uses: actions/checkout@v3
        with:
          path: django_api
      - name: install dependencies
        run: |
          sudo apt-get install python3-pip
          pip3 install virtualenv
      - name: run migrations
        run: |
          cd django_api
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py makemigrations $CI_PROJECT_NAME
          python manage.py migrate
          python manage.py migrate $CI_PROJECT_NAME
          python manage.py check
      - name: test django
        run: python manage.py test # xe